services:
  db:
      image: mysql:5.7
      ports:
        - '3306:3306'
      environment:
        MYSQL_DATABASE: 'db_django'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      restart: always
      volumes:
        - ./bot:/var/lib/mysql